---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: vEOS_4.15.3F
    driver:
      customize:
        memory: 2048

suites:
  - name: veos
    run_list:
      - recipe[eos::default]
    attributes:
