---
driver:
  name: vagrant
  vm_hostname: false
  provision: true

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: vEOS_4.15.3F
    driver:
      vagrantfiles:
        - vagrantfiles/veos.rb
  - name: vEOS-4.16.7M
    driver:
      vagrantfiles:
        - vagrantfiles/veos.rb
  - name: vEOS-lab-4.18.7M
    driver:
      vagrantfiles:
        - vagrantfiles/veos.rb

suites:
  - name: default
    run_list:
      - recipe[eos::default]
    attributes:
  - name: switchconfig_content
    run_list:
      - recipe[eos::default]
      - recipe[eos_test::switchconfig_static]
    attributes:
  - name: switchconfig_template
    run_list:
      - recipe[eos::default]
      - recipe[eos_test::switchconfig_template]
    attributes:
  - name: switchconfig_file1
    run_list:
      - recipe[eos::default]
      - recipe[eos_test::switchconfig_file1]
    attributes:
